name: v36 CI

on:
  push:
    branches:
      - v36
  pull_request:
    branches:
      - v36

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sed up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'


      # Service A
      - name: Install dependencies for Service A
        run: |
          cd service-a
          npm install

      - name: Run tests for Service A
        run: |
          cd service-a
          npm test

      - name: Build Docker image for Service A
        run: |
          docker build -t service-a-image ./service-a

      
      # Service B
      - name: Install dependencies for Service B
        run: |
          cd service-b
          npm install

      - name: Run tests for Service B
        run: |
          cd service-b
          npm test

      - name: Build Docker image for Service B
        run: |
          docker build -t service-b-image ./service-b