name: Dockermulti CI

on:
    push:
        branches:
            - dockermulti

jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build and test builder image
            run: |
              docker build --target builder -t demo-builder:latest .

          - name: Build runtime image
            run: |
              docker build --target runtime -t zowerino/demo:latest .

          - name: Run tests in builder container
            run: |
              docker run --rm demo-builder:latest npm test

          - name: Login to DockerHub
            env:
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              DOCKER_PASSWOPRD: ${{ secrets.DOCKER_PASSWORD }}
            run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          - name: Push runtime image
            run: docker push zowerino/demo:latest