name: Dockermulti CI

on:
    push:
        branches:
            - Vecka-38

jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build test image
            run: docker build -target builder -t v38-builder:latest .

          - name: Run tests in builder container
            run: docker run --rm v38-builder:latest npm test

          - name: Build production image
            run: docker build --target production -t v38-production:latest .

          - name: Push production image to Docker Hub
            run: docker push zowerino/v38:latest