name: CI - Parallel Jobs

on:
  push:
    branches:
      - v36-uppgift4
  pull_request:
    branches:
      - v36-uppgift4

jobs:
  # FRONTEND
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run tests for frontend
        run: |
          cd frontend
          npm test

      - name: Build Docker image for frontend
        run: |
          docker build -t frontend-image ./frontend


          # BACKEND
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run tests for backend
        run: |
          cd backend
          npm test

      - name: Build Docker image for backend
        run: |
          docker build -t backend-image ./backend
