name: Backend Dev CI/CD

on:
  push:
    branches:
      - dev3

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
      ACR_REGISTRY: mybackend.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image (includes tests)
        run: |
          echo "Building Docker image with tag: ${GIT_SHA}"
          docker build -t my-backend:${GIT_SHA} .

      - name: Verify Docker image
        run: docker images

      - name: Tag and push Docker image
        run: |
          echo "Tagging image for ACR push"
          docker tag my-backend${GIT_SHA} ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}
          docker push ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}
          
      - name: Deploy to API-DEV
        run: |
          az containerapp update \
            --name my-backend-dev \
            --resource-group my-rg \
            --image ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}