name: Full CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install dependencies and run tests
              run: |
                echo "Setting up environment..."
                npm install
                echo "Running tests..."
                npm test

            - name: Build project
              run: |
                echo "Building project..."
                npm run build

            - name: Pipeline complete
              run: echo "Full CI Pipeline completed successfully!"