name: Backend Prod CI/CD

on:
  push:
    branches:
      - main3   

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker build -t myregistry.azurecr.io/my-backend:${GIT_SHA} .

      - name: Push Docker image
        run: |
          docker push myregistry.azurecr.io/my-backend:${GIT_SHA}

      - name: Deploy to API-PROD
        run: |
          az containerapp update \
            --name my-backend-prod \
            --resource-group my-rg \
            --image myregistry.azurecr.io/my-backend:${GIT_SHA}