name: Backend Prod CI/CD

on:
  push:
    branches:
      - main3   

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
      ACR_REGISTRY: mybackend.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: ${GIT_SHA}"
          docker build -t my-backend:${GIT_SHA} .

      - name: Tag and Push Docker image
        run: |
          echo "Taggin and pushing Docker image to ACR"
          docker tag my-backend:${GIT_SHA} ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}
          docker push ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}

      - name: Deploy to API-PROD
        run: |
          echo "Deploying Docker image ${GIT_SHA} to API-PROD"
          az containerapp update \
            --name my-backend-prod \
            --resource-group training-moa_group \
            --image ${{ env.ACR_REGISTRY }}/my-backend:${GIT_SHA}